#dev
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#prod
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry-ms-app-service:8761/eureka/


microservices:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment

  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/addOrder