server:
  port: 9196

spring:
  application:
    name: cloud-config-server
  profiles:
    active:
      - prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AhmedBabaAlweimine/order-payment-microservice-project.git
          search-paths: profiles-cloud-config-server
          default-label: feature/CONF-502

