apiVersion: apps/v1
kind: Deployment #kind Deployment
metadata:
  name: cloud-config-server-ms-app-deployement-kubernate
spec:
  selector:
    matchLabels:
      app: cloud-config-server-ms-app
  replicas: 1 # Desired number of pod replicas
  template:
    metadata:
      labels:
        app: cloud-config-server-ms-app
    spec:
      containers:
        - name: cloud-config-server-ms-app
          image: cloud-config-server-service:latest # Nginx image from Docker Hub
          imagePullPolicy: IfNotPresent   #first search in local repo,if not specified alway will look in docker hub
          ports:
            - containerPort: 9196 # Port the container exposes
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---

apiVersion: v1
kind: Service  #kind service
metadata:
  name: cloud-config-server-ms-app-service   # any name here
spec:
  selector:
    app: cloud-config-server-ms-app  #this should be same as deployment selector name
  ports:
    - protocol: "TCP"
      port: 9196
      targetPort: 9196  #this should be same as the Port where the  container exposes up
  type: NodePort