apiVersion: v1
kind: ConfigMap
metadata:
  name: db-order-payment-config
data:
  host: mysql-order-payment-service    #this should be the same as name prvided in :mysqldb-deployment.yaml ,partie Service metadata: name: mysql-service
  dbName: dev
  port: "3307"