apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-order-payment-app
data:
  username: cm9vdA==   # in kubernate use: echo -n 'string' | base64 to get encrypted user password
  password: cm9vdA==