apiVersion: apps/v1
kind: Deployment #kind Deployment
metadata:
  name: payment-ms-app-deployement-kubernate
spec:
  selector:
    matchLabels:
      app: payment-ms-app
  replicas: 1 # Desired number of pod replicas
  template:
    metadata:
      labels:
        app: payment-ms-app
    spec:
      containers:
        - name: payment-ms-app
          image: payment-service:latest # Nginx image from Docker Hub
          imagePullPolicy: IfNotPresent   #first search in local repo,if not specified alway will look in docker hub
          ports:
            - containerPort: 8082 # Port the container exposes
          #resources:
           # requests:
            #  memory: "200Mi"
             # cpu: "250m"
            #limits:
             # memory: "500Mi" #maximum resources the pod can use It won’t exceed this, preventing one pod from starving others.
              #cpu: "500m"   #maximum resources the pod can use It won’t exceed this, preventing one pod from starving others.
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-order-payment-config  #this should match name in meta data of your mysql-configMap.yaml mysql
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-order-payment-config  #this should match name in meta data of your mysql-configMap.yaml mysql
                  key: dbName
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-order-payment-config  #this should match name in meta data of your mysql-configMap.yaml mysql
                  key: port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-order-payment-app  #this should match name in meta data of your mysql-secrets.yaml mysql
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-order-payment-app  #this should match name in meta data of your mysql-secrets.yaml mysql
                  key: password

---

apiVersion: v1
kind: Service  #kind service
metadata:
  name: payment-ms-app-service  # any name here
spec:
  selector:
    app: payment-ms-app  #this should be same as deployment selector name
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082  #this should be same as the Port where the  container exposes up
  type: NodePort