apiVersion: apps/v1
kind: Deployment #kind Deployment
metadata:
  name: registry-ms-app-deployement-kubernate
spec:
  selector:
    matchLabels:
      app: registry-ms-app
  replicas: 1 # Desired number of pod replicas
  template:
    metadata:
      labels:
        app: registry-ms-app
    spec:
      containers:
        - name: registry-ms-app
          image: registry-service:latest # Nginx image from Docker Hub
          imagePullPolicy: IfNotPresent   #first search in local repo,if not specified alway will look in docker hub
          ports:
            - containerPort: 8761 # Port the container exposes

---

apiVersion: v1
kind: Service  #kind service
metadata:
  name: registry-ms-app-service  # any name here
spec:
  selector:
    app: registry-ms-app  #this should be same as deployment selector name
  ports:
    - protocol: "TCP"
      port: 8761
      targetPort: 8761  #this should be same as the Port where the  container exposes up
  type: NodePort