#--------DEV CONFIG -------------------------------##########

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imdbnaukri
    username: root
    password: ahmed

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  #instance:
   # prefer-ip-address: false           # ✅ ensures hostname is used, not pod IP
   # hostname: payment-ms-app-service   # ✅ use your  payment K8s service name in deployement as hostname