#server:
 # port: 8081

#spring:
 # application:
  #  name: order-service
  #profiles:  #moved to bootstrap.yaml
    #active: dev

  #jpa:
    #hibernate:
   #   ddl-auto: update
    #show-sql: true
    #properties:
     # hibernate:
      #  dialect: org.hibernate.dialect.MySQL8Dialect